### ISSUE TITLE
发布需求时不能切换至老师模式，或切换至老师后不能再发布需求，实际情况可切换至老师，并能发布需求

### ISSUE THREAD

**Issue by tonychenta** [wulixu/webedu#104]
![default](https://cloud.githubusercontent.com/assets/8265135/3875128/03b944fa-214d-11e4-87f4-c32f69e7b357.png)

**Comment by zariczhu** [comment]
fixed

**Comment by tonychenta** [comment]
问题没有解决

**Comment by zariczhu** [comment]
done
