### ISSUE TITLE
首页--模块边框下横线没有水平对齐。

### ISSUE THREAD

**Issue by tonychenta** [wulixu/webedu#11]
1.图中两处模块边框下横线没有水平对齐。

![006](https://cloud.githubusercontent.com/assets/8265135/3709850/44362110-1464-11e4-8ef6-a8aa36ed3441.png)

2.图中分类菜单与课程模块没有左对齐。
![007](https://cloud.githubusercontent.com/assets/8265135/3709856/de923456-1464-11e4-92a3-803d47e2d94b.png)

**Comment by xubaojun** [comment]
已经更新，右侧的时习快报的偏差是由于那个新闻那块只显示了4个，系统发布的时候需要有五个新闻。
