### ISSUE TITLE
收藏实习的功能没有实现

### ISSUE THREAD

**Issue by tonychenta** [wulixu/webedu#118]
![001](https://cloud.githubusercontent.com/assets/8265135/3886165/d11109de-21d3-11e4-9cf6-fa2383b0ec16.png)

**Comment by zariczhu** [comment]
加入收藏夹 参照代码
function bookmarkit() 
　　{ 
　　window.external.addFavorite('http://你的网址','你的网站名称') 
　　} 
　　<a href="#" onclick="bookmarkit()">加入收藏夹</a>

**Comment by xubaojun** [comment]
这个功能已经实现了，你可以查看一下浏览器的收藏记录。
