### ISSUE TITLE
首页--浏览器窗口非最大化显示时，界面排版凌乱。

### ISSUE THREAD

**Issue by tonychenta** [wulixu/webedu#12]
当浏览器窗口非最大化显示时，首页、个人中心、选课等所有页面都显示凌乱。

![009](https://cloud.githubusercontent.com/assets/8265135/3709915/befb3428-1467-11e4-9171-5c16600c0c8f.png)

图2:

**Comment by xubaojun** [comment]
这个布局如果浏览器缩小页面元素会自动换行。

**Comment by tonychenta** [comment]
布局都乱了，控件形状也变了，这个也可接受？
![1](https://cloud.githubusercontent.com/assets/8265135/3787359/ad9f99ca-1a12-11e4-917c-9eb5f9f9a7cf.png)
