### ISSUE TITLE
发布评论显示错误

### ISSUE THREAD

**Issue by tonychenta** [wulixu/webedu#123]
我发表的评论
![123](https://cloud.githubusercontent.com/assets/8265135/3889406/36202690-220e-11e4-9478-b32ca1c7b0d7.png)

在购买课程页面的显示
![001](https://cloud.githubusercontent.com/assets/8265135/3889433/7e4dd8ae-220e-11e4-97cd-c9b4bd6dedd6.png)

在我的评论页面的显示
![002](https://cloud.githubusercontent.com/assets/8265135/3889452/b975c4aa-220e-11e4-8af6-be3948ec485f.png)

**Comment by zariczhu** [comment]
课程评分不显示在评价里。评价里人的下面是这个人的等级，与课程没关系。课程评分体现在课程的星星上面
