### ISSUE TITLE
首页--全部课程菜单下的公益课程二级子菜单显示异常

### ISSUE THREAD

**Issue by tonychenta** [wulixu/webedu#13]
当鼠标指向公益课程菜单时，其二级子菜单不能正常显示
![110](https://cloud.githubusercontent.com/assets/8265135/3709943/e9a5a90a-1468-11e4-8517-b6977134363b.png)

**Comment by xubaojun** [comment]
这个地方是由于后台没有数据显示，系统发布到时候需要将这个数据给补充上去。

**Comment by HillsideHung** [comment]
公益是一个特色类别, 应该没有二级菜单.

**Comment by zariczhu** [comment]
关闭
