### ISSUE TITLE
课程发布--添加可授课时间之后再删除，发布课程将失败

### ISSUE THREAD

**Issue by tonychenta** [wulixu/webedu#130]
![111](https://cloud.githubusercontent.com/assets/8265135/3915053/a98ea196-2354-11e4-8d08-10e7e807890e.png)

**Comment by zariczhu** [comment]
ｊｓ判断有点问题

**Comment by tonychenta** [comment]
还是报错，提示你请添加可授课时间

**Comment by xubaojun** [comment]
ok了。
