### ISSUE TITLE
客户提供--根据老师国籍检索，选择国籍一栏无下拉菜单，需手动输入

### ISSUE THREAD

**Issue by tonychenta** [wulixu/webedu#148]
![001](https://cloud.githubusercontent.com/assets/8265135/3978574/7c6413aa-2849-11e4-9bc5-d74ba0a926e6.png)

**Comment by xubaojun** [comment]
先暂时让用户手动输入吧，用下拉框的话，数据比较死。

**Comment by zariczhu** [comment]
老师所在地去掉
