### ISSUE TITLE
客户bug--学生自己查看已经发布课程需求时，信息对应有误

### ISSUE THREAD

**Issue by tonychenta** [wulixu/webedu#152]
![001](https://cloud.githubusercontent.com/assets/8265135/3978939/7d0a6dfe-284e-11e4-965e-649b21c52e2f.png)

**Comment by xubaojun** [comment]
ui的上课日期我已经修改，朱哥，将那个上课的时间点给输出出来。

**Comment by zariczhu** [comment]
done
