### ISSUE TITLE
客户bug--个人简历-教育背景-结束时间空白情况下，系统提示信息定位不准确

### ISSUE THREAD

**Issue by tonychenta** [wulixu/webedu#155]
![001](https://cloud.githubusercontent.com/assets/8265135/3979241/4263de52-2852-11e4-8c3c-43827c524b22.png)

**Comment by tonychenta** [comment]
开始时间空白情况下，系统提示信息同样定位不准确

**Comment by xubaojun** [comment]
为空表示至今

**Comment by tonychenta** [comment]
现在出现一个乱码弹出框
