### ISSUE TITLE
客户--在学生填写投诉原因大于字数限制之后，弹出一个未知且要打开或保存的文件

### ISSUE THREAD

**Issue by tonychenta** [wulixu/webedu#156]
![001](https://cloud.githubusercontent.com/assets/8265135/3979311/00d700e4-2853-11e4-9d6c-1828788cdeb3.png)
当输入投诉文字超过500，没有提示信息，跳转至入下页面：

{"info":"\u9a8c\u8bc1\u5931\u8d25","status":0,"data":{"Content":["Content \u592a\u957f (\u6700\u5927\u503c\u4e3a 500 \u5b57\u7b26\u4e32)."]}}

**Comment by xubaojun** [comment]
已经重新修复
