### ISSUE TITLE
教学经历结束时间为空提示信息有误

### ISSUE THREAD

**Issue by tonychenta** [wulixu/webedu#166]
![001](https://cloud.githubusercontent.com/assets/8265135/3980585/202b65d2-2864-11e4-98ef-21cf9f3dba3e.png)

**Comment by tonychenta** [comment]
课程结束时间为空时，没有提示信息

**Comment by xubaojun** [comment]
教学经历的结束时间可以为空，为空表示到至今。

**Comment by tonychenta** [comment]
第二个问题没有解决，使用del 键back space键无法删除时间
