### ISSUE TITLE
名词在教学简历与课程购买两处不一致

### ISSUE THREAD

**Issue by tonychenta** [wulixu/webedu#173]
![001](https://cloud.githubusercontent.com/assets/8265135/3981239/e841e92c-286b-11e4-92ec-5c8e08b90d03.png)

**Comment by tonychenta** [comment]
![002](https://cloud.githubusercontent.com/assets/8265135/3981324/f4c12964-286c-11e4-84bb-4bafd8fc6540.png)

**Comment by zariczhu** [comment]
统一改成老师身份。
