### ISSUE TITLE
客户bug--我的评价--下拉框中无差评选项，并且无法筛选。

### ISSUE THREAD

**Issue by tonychenta** [wulixu/webedu#181]
![123](https://cloud.githubusercontent.com/assets/8265135/3991382/d4e9bf42-28e0-11e4-9a4c-cbfb64b6cc91.png)

**Comment by zariczhu** [comment]
我后台已经改好，你前台看看下拉框变换的时候传个参数过来$_GET["point"]，如果全部显示就不传
