### ISSUE TITLE
客户bug--发布课程填写信息页面，课程类别大类时习职场对应的小类别下拉框没有数据项

### ISSUE THREAD

**Issue by tonychenta** [wulixu/webedu#183]
![111](https://cloud.githubusercontent.com/assets/8265135/3991516/54a5494c-28e4-11e4-87b4-d9a7de9736fa.png)

**Comment by tonychenta** [comment]
另一个分类“兴趣爱好”下也没有二级类别

**Comment by xubaojun** [comment]
黄哥，你需要添加一下数据。

**Comment by xubaojun** [comment]
黄哥，你需要添加一下数据。

**Comment by HillsideHung** [comment]
应该存在此状况,有可能用户未添加二级分类数据.
