### ISSUE TITLE
个人信息模块--个人简历与教学简历的保存功能失败。

### ISSUE THREAD

**Issue by tonychenta** [wulixu/webedu#20]
1.正确填写个人资料与教学简历后，保存失败。
2.两处失败信息的位置应保持一致。
![3](https://cloud.githubusercontent.com/assets/8265135/3710399/85ab749a-1489-11e4-9134-b6c40ffe5b24.png)

**Comment by tonychenta** [comment]
另一张图传不上去

**Comment by zariczhu** [comment]
能否具体一点
