### ISSUE TITLE
绑定qq账号并激活之后，重新通过qq登陆，再次跳转至qq绑定页面，无法正常登陆

### ISSUE THREAD

**Issue by tonychenta** [wulixu/webedu#229]
![123](https://cloud.githubusercontent.com/assets/8265135/4417948/7e537768-455a-11e4-97b9-760b528692a4.png)
付现步骤：
1.点击图中的qq登陆
2.输入qq账号密码登陆，跳转至绑定账号页面
3.输入保存，跳转至激活页面
4.激活后，再次通过步骤1的qq登陆，登陆失败，跳转至绑定页面

**Comment by zariczhu** [comment]
无法再现
