### ISSUE TITLE
支付页面--时间币帐户金额不足时点击确认支付，应该弹出提示余额不足信息

### ISSUE THREAD

**Issue by tonychenta** [wulixu/webedu#233]
![qq 20140929200631](https://cloud.githubusercontent.com/assets/8265135/4441301/21906e0e-47d1-11e4-9f8d-b4156003e0b0.jpg)

**Comment by xubaojun** [comment]
目前余额不足的时候，会直接选到支付宝平台。

**Comment by tonychenta** [comment]
使用支付宝支付时候没有跳转到支付宝页面
