### ISSUE TITLE
个人简历--如果我只填写教育背景 能够保存成功，但是不能成为老师

### ISSUE THREAD

**Issue by tonychenta** [wulixu/webedu#237]
1.如果我只填写教育背景 能够保存成功，但是不能成为老师
2.个人简历这块没有区分哪些是必填项

![1234](https://cloud.githubusercontent.com/assets/8265135/4514979/3993bc4c-4b9e-11e4-85ff-29bddb5a267b.png)

**Comment by zariczhu** [comment]
done
