### ISSUE TITLE
发布课程--选择或填写内容有上下不符时，应对可能出错行加框，并在后面提示出错信息

### ISSUE THREAD

**Issue by tonychenta** [wulixu/webedu#238]
1.出错没有加红框的选项有：包括标题、时间比、科目类别、可授课时间、课程描述、
2.科目类别为空的出错信息描述u准确，不是课程类别，改为科目类别
![1112](https://cloud.githubusercontent.com/assets/8265135/4515015/0c38e75a-4ba2-11e4-87f8-4db6061b336c.png)

**Comment by xubaojun** [comment]
这个地方目前只加了，标题，其他的选项，添加了不好看。
