### ISSUE TITLE
个人中心导航--在财务信息页面，统计消费数额时,当不输入开始时间或截止时间，应有提示信息。

### ISSUE THREAD

**Issue by tonychenta** [wulixu/webedu#25]
设开始时间为空，点击“开始统计”，应有提示信息“请输入开始时间”；
设结束时间为空，点击“开始统计”，应有提示信息“请输入截止时间”

**Comment by xubaojun** [comment]
这个地方如果没有时间选择，说明就是查询所有的记录。
