### ISSUE TITLE
首页细节修改

### ISSUE THREAD

**Issue by jxtp040424** [wulixu/webedu#329]
![qq 20141114094208](https://cloud.githubusercontent.com/assets/9733483/5040045/e201b88e-6be2-11e4-91c6-de472a114148.png)

![qq 20141114094651](https://cloud.githubusercontent.com/assets/9733483/5040094/7af85e26-6be3-11e4-870c-0800bd64ac9b.png)
首页下部分大类中的课程，上下间距太大（参照UI)，实线也没有齐平.

**Comment by zariczhu** [comment]
保军 看看呢
