### ISSUE TITLE
个人信息的国家

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#332]
![image](https://cloud.githubusercontent.com/assets/9734724/5118589/8a64421a-709f-11e4-99c3-f775ecc8be0f.png)
麻烦 请把个人信息里面国籍改成Internet里面的时区，如下图：
![image](https://cloud.githubusercontent.com/assets/9734724/5118666/83411d86-70a0-11e4-83fc-2662c1d5e69b.png)

**Comment by zariczhu** [comment]
按照邮件里的国家来

**Comment by zariczhu** [comment]
然后 顺序也按照邮件里来，大洲要放进去，大洲下面没有国家就放州的名字

**Comment by HillsideHung** [comment]
数据库 update
