### ISSUE TITLE
ie页面出现问题

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#338]
![image](https://cloud.githubusercontent.com/assets/9734724/5160326/42068f14-73c4-11e4-917c-cdbaae901e51.png)
IE的这个怎么是正方形的
![image](https://cloud.githubusercontent.com/assets/9734724/5160327/5519556e-73c4-11e4-98c8-60225721073e.png)
查下为什么IE上面的导航和最上面的没有显示

**Comment by zariczhu** [comment]
你是IE几？ 然后 【IE上面的导航和最上面的没有显示】 这句话什么意思

**Comment by pl01956257** [comment]
IE8 导航上面的文字没显示啊还有最上面 就是首页 我要求学什么的文字以及最上面的登录注册什么文字都没有 你看我发的那个图片

**Comment by zariczhu** [comment]
保军 看一下

**Comment by zariczhu** [comment]
这个问题因为ie版本太低，我们系统不会适应ie8的
