### ISSUE TITLE
后台用户管理

### ISSUE THREAD

**Issue by zariczhu** [wulixu/webedu#363]
1.把其他设置改为用户账户管理，添加助学币管理。
2.点击查看后进入的内页右边全部加上用户名（一直显示）。
3.时间币管理里用户名不要了。
4.在用户管理后面加个状态显示：已激活/未激活
5.把用户管理-其他设置，改为用户账户管理，界面出来，可以查看用户时间币流水
查看流水的记录，可以点击查看详细记录

**Comment by zariczhu** [comment]
最新业务
1.把其他设置改为用户账户管理。
2.点击查看后进入的内页右边全部加上用户名（一直显示）。
3.时间币管理里用户名不要了。
4.在用户管理后面加个状态显示：已激活/未激活
5.把用户管理-其他设置，改为用户账户管理，界面出来，可以查看用户时间币流水
查看流水的记录，可以点击查看详细记录

**Comment by HillsideHung** [comment]
用户管理状态在jpg上没有....

**Comment by zariczhu** [comment]
4.在用户管理后面加个状态显示：已激活/未激活

**Comment by HillsideHung** [comment]
done 用户管理改称会员管理
