### ISSUE TITLE
后台，课程排名管理

### ISSUE THREAD

**Issue by zariczhu** [wulixu/webedu#372]
需要为课程添加一个唯一的编号，以一定的规则，后台可以通过编号查找改课程
排名要用到首页和我是学生，实现课程推广功能
管理员可以通过课程的编号，查找特定课程
KC201410140001
(KC年月日最后四位自增）

**Comment by HillsideHung** [comment]
增加课程编号栏.

**Comment by zariczhu** [comment]
课程编号不需要超链接。

**Comment by HillsideHung** [comment]
建议课程编号和投诉编号长度一致 -> KC年月日 小时 最后四位自增

**Comment by xubaojun** [comment]
栏位已经加上，将后台数据给集成上去。
