### ISSUE TITLE
第三登陆 12/08

### ISSUE THREAD

**Issue by zariczhu** [wulixu/webedu#377]
第三方登录直接进入爱时习跳出设置密码的小窗口。（见第三方设置密码.jpg)
.当第三方登录时，首页上放默认的用户名为第三方用户名。当用户完善好个人信息后，原先默认的用户名自动变为个人信息中填写的用户名。

**Comment by xubaojun** [comment]
UI已经弄好，需要做一下功能集成

**Comment by zariczhu** [comment]
宝军 做一下两个密码框的输入check，及错误消息显示
