### ISSUE TITLE
首页--时间选择效果应改为具体时间

### ISSUE THREAD

**Issue by tonychenta** [wulixu/webedu#38]
![005](https://cloud.githubusercontent.com/assets/8265135/3733131/0d13d080-1705-11e4-8c57-384a33e4fef1.png)
![006](https://cloud.githubusercontent.com/assets/8265135/3733263/28e8710c-1706-11e4-9e38-e0e34da4621c.png)

**Comment by xubaojun** [comment]
教育那块的时间需要定位到日期的。

**Comment by tonychenta** [comment]
简历里面的教育经历时间不应该精确到日，次问题有两处，个人简历与教育经历，参考下图：

![1](https://cloud.githubusercontent.com/assets/8265135/3796441/799fa710-1bc9-11e4-9a52-a1421852233e.png)

**Comment by xubaojun** [comment]
这块先这样了。
