### ISSUE TITLE
结算申请01-04 12/06

### ISSUE THREAD

**Issue by zariczhu** [wulixu/webedu#393]
![qq 20141125163021](https://cloud.githubusercontent.com/assets/8265166/5258304/26f9e45c-7a2f-11e4-9c8f-c17f7b7c9c2f.png)

**Comment by zariczhu** [comment]
保军 按照ui 这个页面也要改一下

**Comment by pl01956257** [comment]
结算提醒这一项有4个页面，都有文字的小修改请注意  
再麻烦注意下帐和账字 这个Sammi 特别提醒的
谢谢

**Comment by xubaojun** [comment]
UI 已经更新，做一下功能修改。

**Comment by zariczhu** [comment]
done
