### ISSUE TITLE
登录注册

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#396]
（1）.注册完成后进入爱时习后右上角未显示注册的邮箱/手机以及提醒您的帐户尚未激活，请点击激活帐号（我注册完成后进入爱时习时，页面呈现一个未登录状态，需要我再登录一遍才会显示注册的邮箱/手机以及提醒内容） （2）.帐号在未激活的状态下购买课程时页面上提示请先完善个人信息基本资料在跳转至个人信息页面。（3）.老师完成个人简历但未完善完个人信息时发布课程页面上提示请完善个人信息基本资料在跳转至个人信息页面。（4）.登录/注册页面的第三方登录的三个图标未按UI修改

**Comment by zariczhu** [comment]
done
