### ISSUE TITLE
登录页面

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#397]
![qq 20141202145534](https://cloud.githubusercontent.com/assets/9734724/5258936/94d3fa36-7a33-11e4-8936-c39dabb2e115.png)

登录页面的验证码怎么没有了需加上（上周还有的这周就没有，是不是不小心弄掉了）   顺便把右边第三方的图标位置什么一起改了吧
第三方图标按注册01的修改
验证码的按下面那张的加上
![default](https://cloud.githubusercontent.com/assets/9734724/5258984/7fa55708-7a34-11e4-9036-4597c4aa6998.jpg)

**Comment by zariczhu** [comment]
在看看有没有问题
