### ISSUE TITLE
登陆页面（输入帐号问题）

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#399]
![qq 20141202150339](https://cloud.githubusercontent.com/assets/9734724/5259048/594f531e-7a35-11e4-9739-3ab4c9d711f1.jpg)

这里输完邮箱按回车就显示密码错误
而且自动登录打勾不起作用

**Comment by zariczhu** [comment]
保军 看看

**Comment by xubaojun** [comment]
回车键是的问题，我已经修改，自动登录的是后台实现的。
