### ISSUE TITLE
学生中心下的个人信息中的个人简历资料填完之后点击保存不成功，弹出一个窗口，说插入数据库不正确

### ISSUE THREAD

**Issue by JacindaChen** [wulixu/webedu#404]

**Comment by HillsideHung** [comment]
前台没有检查教育背景的时间. 控件可以输入也可以start 后于 end 时间.

**Comment by HillsideHung** [comment]
![qq 20141202213304](https://cloud.githubusercontent.com/assets/8265197/5263340/e879993e-7a6a-11e4-8228-8b6d38e47200.jpg)

**Comment by HillsideHung** [comment]
https://github.com/wulixu/webedu/issues/412

合并到#412
