### ISSUE TITLE
未完善个人信息购买课程问题

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#405]
![qq 20141202155502](https://cloud.githubusercontent.com/assets/9734724/5259485/f3157392-7a3b-11e4-9c54-885ab41efcfb.png)
游览器：搜狗 360
提醒框没有只有文字
跳转过快 感觉只有1秒 文字都没看清就跳转了
谷歌的话提醒框有出现的但是跳转还是太快 设置5秒吧

**Comment by zariczhu** [comment]
保军 看看呢，是不是浏览器的问题
