### ISSUE TITLE
手机QQ微信三个图标问题

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#420]
![qq 20141203113807](https://cloud.githubusercontent.com/assets/9734724/5275575/78960d92-7ae1-11e4-8586-a3278a82a4f2.png)
这个手机 QQ微信的三个图标之前说了 把我们的那个QQ图标换成腾讯自带QQ图标 
不是现在这种有2个QQ了
然后记得QQ是排中间

**Comment by zariczhu** [comment]
done
