### ISSUE TITLE
所有登录“账户名”改成“帐户名”，但与支付相关处（支付、提现）显示“账户名”，UI本身就有问题

### ISSUE THREAD

**Issue by JacindaChen** [wulixu/webedu#422]
![3](https://cloud.githubusercontent.com/assets/10020864/5276452/adcd161a-7af3-11e4-8dc3-cdbb52072450.jpg)
![1](https://cloud.githubusercontent.com/assets/10020864/5276453/addb1788-7af3-11e4-88b2-0eaa5d559291.jpg)
![2](https://cloud.githubusercontent.com/assets/10020864/5276454/addeebb0-7af3-11e4-93e8-0102c4aad9f5.jpg)
还有激活邮件里面也有问题，我就不截图了，你看下

**Comment by HillsideHung** [comment]
已经全盘查过一遍,如果再有发现,请open并附图.
