### ISSUE TITLE
咨询投诉

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#430]
![qq 20141204094658](https://cloud.githubusercontent.com/assets/9734724/5292588/f3232f50-7b9e-11e4-8dbd-7a0086eb0569.jpg)

**Comment by zariczhu** [comment]
保军 ui先改一下i，那个状态然后给我

**Comment by xubaojun** [comment]
ui 已经修改。

**Comment by zariczhu** [comment]
done
