### ISSUE TITLE
首页页面BUG

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#432]
![qq 20141204112554](https://cloud.githubusercontent.com/assets/9734724/5293339/c06e5592-7baa-11e4-9194-9f3a275d1c50.jpg)
![qq 20141204112602](https://cloud.githubusercontent.com/assets/9734724/5293340/c0709762-7baa-11e4-9c4a-e8075320dc48.jpg)
![qq 20141204112610](https://cloud.githubusercontent.com/assets/9734724/5293341/c074bd10-7baa-11e4-84dc-727df58f3610.jpg)

**Comment by zariczhu** [comment]
保军看看
