### ISSUE TITLE
我要助学BUG

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#440]
![qq 20141205091056](https://cloud.githubusercontent.com/assets/9734724/5309420/e0d7cee4-7c5e-11e4-852c-6fa8096d79f1.png)
这个是不是我要描述里面插的图片
怎么那么大

**Comment by zariczhu** [comment]
这个也看看呢

**Comment by xubaojun** [comment]
这个地方控件可以设置图片大小。
![Uploading QQ图片20141205150504.jpg . . .]()
