### ISSUE TITLE
课程付款页面有跟UI不一致的地方

### ISSUE THREAD

**Issue by JacindaChen** [wulixu/webedu#446]
![12](https://cloud.githubusercontent.com/assets/10020864/5310518/728972b0-7c6f-11e4-95dd-bff08c76be34.jpg)

**Comment by xubaojun** [comment]
这个地方的卖家昵称朱哥，确认一下。其他的不是bug都是后来调整的。

**Comment by zariczhu** [comment]
这个页面不管它，客户提供的页面肯定是不合理的
