### ISSUE TITLE
修改手机号码页面有跟UI不完全一致的地方

### ISSUE THREAD

**Issue by JacindaChen** [wulixu/webedu#449]
![16](https://cloud.githubusercontent.com/assets/10020864/5310680/9679f98a-7c72-11e4-8870-0d43e7605979.jpg)

**Comment by JacindaChen** [comment]
修改邮箱之后也是同样的问题，记得一起改了

**Comment by zariczhu** [comment]
这里跟客户确认过了，不需要用星号代替
