### ISSUE TITLE
我要充值中与UI不完全一致

### ISSUE THREAD

**Issue by JacindaChen** [wulixu/webedu#455]
![21](https://cloud.githubusercontent.com/assets/10020864/5311979/296c6b2e-7c8c-11e4-8482-aece9cbaf447.jpg)

**Comment by JacindaChen** [comment]
![22](https://cloud.githubusercontent.com/assets/10020864/5312009/81ba9b02-7c8c-11e4-912b-2664e7772952.jpg)

**Comment by xubaojun** [comment]
这个地方是客户后台确定的是订单号。
