### ISSUE TITLE
第三方登陆成功后有个灰色的“个人中心”按钮点击之后还是回到登陆页面，详情见截图

### ISSUE THREAD

**Issue by JacindaChen** [wulixu/webedu#460]
![26](https://cloud.githubusercontent.com/assets/10020864/5312552/1762adf2-7c97-11e4-9181-d969958bd7e6.jpg)

**Comment by zariczhu** [comment]
done,就是放用户昵称，不是放数字，另外可以点击个人中心进个人信息了
