### ISSUE TITLE
页面出现BUG

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#463]
![46 2ag7 c dutsd7 liz 5j](https://cloud.githubusercontent.com/assets/9734724/5372796/b22b4998-8089-11e4-9495-131c2c0abbe6.jpg)
新用户注册登录后（学生中心）完善基本资料后点击了课程管理跳出这个页面

**Comment by pl01956257** [comment]
这个页面应该以前就删掉了

**Comment by zariczhu** [comment]
改成了个人简历页面
