### ISSUE TITLE
首页BUG

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#468]
![qq 20141212093939](https://cloud.githubusercontent.com/assets/9734724/5405668/427d8c9a-81e3-11e4-88a5-6505cf21e3d0.jpg)
生活社区那一块对齐横着的红线
所有下面的二级模块都要对齐竖着的红线
看下首页UI都线在改 别又改错

**Comment by zariczhu** [comment]
说了这里 只能放3排，放4排会影响美观
