### ISSUE TITLE
订单详情BUG

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#474]
![qq 20141215135736](https://cloud.githubusercontent.com/assets/9734724/5431375/a28d0eea-8462-11e4-9a5a-37212fe78297.png)
昵称改为用户名

**Comment by pl01956257** [comment]
![qq 20141215135912](https://cloud.githubusercontent.com/assets/9734724/5431396/2807c128-8463-11e4-8284-a6f842f25a58.png)
QQ图标也要换一下

**Comment by xubaojun** [comment]
check 一下，原先的昵称下面是不是输出的用户名。
