### ISSUE TITLE
课程管理BUG

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#477]
免费与收费的课程在被用户购买后 
课程描述，先修知识，参考知识都应该不能修改保存
应该是保存新增

现在页面上做的是课程被后买后能修改保存

**Comment by zariczhu** [comment]
有这个需求？

**Comment by pl01956257** [comment]
对，她们现在提出来说课程被购买后也不能修改课程描述，先修知识，参考知识

**Comment by xubaojun** [comment]
已经做了相应的处理，当该课程被购买以后，相应的控件已经被disable掉了。
