### ISSUE TITLE
首页BUG

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#491]
![image](https://cloud.githubusercontent.com/assets/9734724/5466756/f8cf66dc-85ec-11e4-94fd-d0310413749b.png)

**Comment by zariczhu** [comment]
什么情况下会出现？什么浏览器

**Comment by pl01956257** [comment]
所有游览器都出现了 你点生活社会 然后把页面往下移点就能看到

**Comment by zariczhu** [comment]
保军，看一下 应该是白底不应该是透明的
