### ISSUE TITLE
创建白板时间BUG

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#496]
![_guu1 oul1mbwpjn4bekw t](https://cloud.githubusercontent.com/assets/9734724/5483251/d3173592-86a9-11e4-9386-c3382ed58307.jpg)
12月16日的课到12月18日还能创建房间，看下是不是BUG了

**Comment by zariczhu** [comment]
这个问题是因为服务器时间和数据库服务器时间 有误差，现在已修改
