### ISSUE TITLE
我的时间-时间周期-时间段填写不合理

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#500]
![qq 20141219133749](https://cloud.githubusercontent.com/assets/9734724/5500670/8ef871ce-8784-11e4-891b-0dfc68cf2cd8.png)
如查询的时间周期错误，需提醒用户：您选择的时间有误，请重新选择。或者后面日期框控件就不让选择之前的日期

**Comment by xubaojun** [comment]
已经做相应的处理
