### ISSUE TITLE
多处页面出现BUG

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#502]
![qq 20141219155751](https://cloud.githubusercontent.com/assets/9734724/5501670/9ebef55a-8799-11e4-96dd-967dc2fc135f.jpg)
多处页面都出现这个问题
请仔细检查，不要出现类似问题

**Comment by zariczhu** [comment]
详细的步骤？

**Comment by zariczhu** [comment]
是改新的问题，引起的，现在已经修改好
