### ISSUE TITLE
我的帐户BUG

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#503]
![qq 20141222105539](https://cloud.githubusercontent.com/assets/9734724/5520836/69408c36-89c9-11e4-94a2-e8ef75a06efe.jpg)
![qq 20141222105511](https://cloud.githubusercontent.com/assets/9734724/5520833/586dd58a-89c9-11e4-845b-725688b34e53.jpg)
买了某节课，上完课后，在我的帐户里面出现了2个相同的订单编号的课时
账号密码:2916472245@qq.com   123456

**Comment by zariczhu** [comment]
done
