### ISSUE TITLE
投诉管理与UI不完全一致，投诉状态的显示方式忘记在图中标了

### ISSUE THREAD

**Issue by JacindaChen** [wulixu/webedu#506]
![default](https://cloud.githubusercontent.com/assets/10020864/5522602/596350dc-89f6-11e4-9bf9-3d5f4bf20cca.jpg)

**Comment by JacindaChen** [comment]
![11](https://cloud.githubusercontent.com/assets/10020864/5523292/7cd55f8c-8a01-11e4-8027-da8d1f42d5f4.jpg)

**Comment by HillsideHung** [comment]
保军添加一下后给我.

**Comment by HillsideHung** [comment]
1) 投诉编号不全是数据问题, 这个会再修改后自动生成,不需要修改.
保军添加一下后给我.

**Comment by HillsideHung** [comment]
三个过滤按钮已加.
