### ISSUE TITLE
快讯图文管理中的编辑文章界面与UI不一致

### ISSUE THREAD

**Issue by JacindaChen** [wulixu/webedu#508]
![1](https://cloud.githubusercontent.com/assets/10020864/5522841/ba7f3d50-89fa-11e4-800f-ecc1360734e3.jpg)
![2](https://cloud.githubusercontent.com/assets/10020864/5522860/375d8048-89fb-11e4-9fff-c6094c0390a9.jpg)

**Comment by JacindaChen** [comment]
这个发布日期UI里面说要用日历控件修改，不知道是不是还没做，一起看下哈

**Comment by HillsideHung** [comment]
保军添加黑色的那块就好,其他的已经修正.
