### ISSUE TITLE
快讯图文管理中的图文广告页面

### ISSUE THREAD

**Issue by JacindaChen** [wulixu/webedu#509]
![3](https://cloud.githubusercontent.com/assets/10020864/5522980/0dbdf00e-89fd-11e4-9fbe-1f093e3615dc.jpg)

**Comment by HillsideHung** [comment]
选中已经修正, 后一个结束日期已经去掉. 查询 已经改成 "搜索"  排序没错看 05.jpg的注解.

请朱哥问一下那个蓝色链接到那个页面.
