### ISSUE TITLE
投诉管理里面的授课日志窗口弹出时背景没有变成半透明

### ISSUE THREAD

**Issue by JacindaChen** [wulixu/webedu#511]
![5](https://cloud.githubusercontent.com/assets/10020864/5523240/b48298e2-8a00-11e4-845c-b13997510afe.jpg)

**Comment by JacindaChen** [comment]
忘记说了，授课日志的窗口里面的“内容”下面，UI中是“进入课堂”，而这边是“进入房间”，你看看要不要改改

**Comment by xubaojun** [comment]
这个地方的背景半透明的没什么意义，实现起来也比较麻烦，就这样吧。
