### ISSUE TITLE
时习快讯和图文广告里面的删除按钮点击后出现乱码页面

### ISSUE THREAD

**Issue by JacindaChen** [wulixu/webedu#513]
![100](https://cloud.githubusercontent.com/assets/10020864/5544916/c154220e-8b4d-11e4-8b2d-6be4fa615bd1.jpg)
![101](https://cloud.githubusercontent.com/assets/10020864/5544918/c60dea14-8b4d-11e4-8fb0-e55d4f4f84be.jpg)

**Comment by HillsideHung** [comment]
保军看一下, ajax执行成功,这边你忘了处理了吧.
