### ISSUE TITLE
授课时间选择查询 有误BUG

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#514]
![qq 20141224104610](https://cloud.githubusercontent.com/assets/9734724/5545361/dd5624d6-8b5a-11e4-92fd-67bd9a3b5169.jpg)
如图

**Comment by zariczhu** [comment]
如果选择了 12-18点，表示学生的上课时间与选择的时间有重叠部分就可以，截图里面的9点到12点这个边界条件可以改一下

**Comment by pl01956257** [comment]
我去问下她们具体要怎么改

**Comment by pl01956257** [comment]
9点到12点这个边界不算 重叠时间部分可以

**Comment by zariczhu** [comment]
done
