### ISSUE TITLE
首页 点击跳转页面错误BUG

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#515]
学习辅导里 选择对应的选项 如高中英语之后跳出的界面 并非对应的高中英语  而是所有的课程
![qq 20141224111839](https://cloud.githubusercontent.com/assets/9734724/5545494/eb37f918-8b5e-11e4-970f-e2e8380d5945.jpg)

**Comment by pl01956257** [comment]
课程分类里面所有的点击都会跳到所有课程的检索页

**Comment by zariczhu** [comment]
done
