### ISSUE TITLE
点击“我收到的投诉”出现代码错误

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#516]
![image](https://cloud.githubusercontent.com/assets/9734724/5546049/bce455e8-8b72-11e4-93e5-d34209eadc76.png)
![image](https://cloud.githubusercontent.com/assets/9734724/5546053/d748f876-8b72-11e4-825f-e41a6cdbfdb2.png)

**Comment by zariczhu** [comment]
用户名 和密码？

**Comment by pl01956257** [comment]
1049735891@qq.com     echo404158

**Comment by zariczhu** [comment]
不能重现
