### ISSUE TITLE
个人简历BUG

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#517]
![image](https://cloud.githubusercontent.com/assets/9734724/5546222/9f619120-8b77-11e4-94f1-6dc182562d89.png)

个人简历部分所有的都不进行填写，知识通过删减一些空格，如下面的样子，可以保存简历成为老师。
之前提过这个BUG，教育背景或工作背景必须有一条才能保存为老师

**Comment by pl01956257** [comment]
1049735891@qq.com echo404158

**Comment by zariczhu** [comment]
无法重现
