### ISSUE TITLE
手机绑定

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#522]
![7tdrvu4 s isaq67z6 xrf](https://cloud.githubusercontent.com/assets/9734724/5546778/7b16cd86-8b85-11e4-88e3-b6e71e97a7b8.png)
情况是填完验证码后提示我手机号重复，然后我重新填写手机号，点“获取密码”这里还是打对勾
IE11  用户名 sammimo926@hotmail.com  密码 MJN0814

**Comment by zariczhu** [comment]
done
