### ISSUE TITLE
登陆页面

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#523]
在登录页面输入邮箱和密码，先出现两个都是对勾，然后再出现错误提示“不存在此用户
用户名 sammimo926@hotmail.com
密码 MJN0814
IE11

**Comment by pl01956257** [comment]
上面的账号密码错了，是这个 帐号是sammimo@ashixi.com，密码是MJN0814

**Comment by zariczhu** [comment]
未知原因，现在好像可以了
