### ISSUE TITLE
注册绑定

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#525]
![image](https://cloud.githubusercontent.com/assets/9734724/5552692/ff2251d6-8c43-11e4-8059-eda1fafb2117.png)
![image](https://cloud.githubusercontent.com/assets/9734724/5552690/fbc3c830-8c43-11e4-8185-95443f79e3a7.png)
邮箱注册后绑定了手机号码。用手机号码登录，系统提示没有此账户；用手机号码注册，系统提示号码已经注册。
IE11 18721678626 echo404158

**Comment by zariczhu** [comment]
无法再现
