### ISSUE TITLE
手机验证

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#526]
![image](https://cloud.githubusercontent.com/assets/9734724/5552715/ed461f50-8c44-11e4-95fc-bb8b6dc70014.png)
![image](https://cloud.githubusercontent.com/assets/9734724/5552717/ef03fa42-8c44-11e4-8f27-0fb936bc0349.png)

手机验证出现的提示，不符合实际情况。比如：请输入验证码。(IE11 18888295437 echo404158)

**Comment by zariczhu** [comment]
done
