### ISSUE TITLE
回复需求

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#531]
![image](https://cloud.githubusercontent.com/assets/9734724/5555528/4405c2d8-8cee-11e4-8fe1-867a9e289ca9.png)
![image](https://cloud.githubusercontent.com/assets/9734724/5555542/e851adc0-8cee-11e4-9bfd-dbd38a72d553.png)
![image](https://cloud.githubusercontent.com/assets/9734724/5555543/ebe07052-8cee-11e4-800f-f06de4f2fe50.png)
点击回复，下方出现对号；关闭后，再次点开，下方还是有对号，但是回复按钮不管，用登录另一个账号，查看回复，但是回复信息为0。（IE11 1049735891@qq.com echo404158(发布需求) 1727843049@qq.com echo404158

**Comment by zariczhu** [comment]
done
