### ISSUE TITLE
评价管理

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#533]
![image](https://cloud.githubusercontent.com/assets/9734724/5555547/24a3fab2-8cef-11e4-8ef8-9014fdd478ec.png)
![image](https://cloud.githubusercontent.com/assets/9734724/5555548/273f7102-8cef-11e4-8a73-13de959492c4.png)
提示内容不对。改为：您目前未收到此类评价！（IE11）

**Comment by zariczhu** [comment]
done
