### ISSUE TITLE
前后台用户信息修改不同步

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#537]
最早注册的邮箱帐户：sammimo926@hotmail.com
原先设置的用户名是：Sammi
现在我在个人信息中增加微信信息，保存时要求用户名要6～20字符，所以改为sammimomo，前台信息已修改成功，如下：
![image](https://cloud.githubusercontent.com/assets/9734724/5608294/5f12257a-94ba-11e4-8e84-a411773d6917.png)
后台用户名查询无结果：
![image](https://cloud.githubusercontent.com/assets/9734724/5608295/65c9754e-94ba-11e4-9088-c9e8e131f2b4.png)
后台用邮箱查询结果：
![image](https://cloud.githubusercontent.com/assets/9734724/5608297/6ee29cd2-94ba-11e4-9b5e-d99ab1e5fe6f.png)

**Comment by HillsideHung** [comment]
不能再现.
