### ISSUE TITLE
我的收藏

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#538]
![image](https://cloud.githubusercontent.com/assets/9734724/5608305/f3f3b0be-94ba-11e4-945a-6b4acaa05312.png)
S,E大写（与订单等其他地方显示一致）, 老师信息三联标无显示
![image](https://cloud.githubusercontent.com/assets/9734724/5608311/2d7048f2-94bb-11e4-85a2-c19ca3e5522c.png)
取消关注QQ图标不相关（这里图标应该是放在老师姓名下面），头像未修改圆形，另外头像有超链接，但是空白页。关注老师的基本信息不全。

**Comment by zariczhu** [comment]
done
