### ISSUE TITLE
找课程--课程索引显示错误

### ISSUE THREAD

**Issue by tonychenta** [wulixu/webedu#54]
![default](https://cloud.githubusercontent.com/assets/8265135/3798517/9d69ff30-1be5-11e4-994c-80c454365b01.png)

**Comment by zariczhu** [comment]
fixied

**Comment by tonychenta** [comment]
请调整下字体，有点小
![111](https://cloud.githubusercontent.com/assets/8265135/3852594/fc88cb0c-1ead-11e4-8ba7-9692fdaf3a9a.png)
