### ISSUE TITLE
老师的级别状态不同

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#540]
![image](https://cloud.githubusercontent.com/assets/9734724/5608330/8430aca4-94bb-11e4-9bd7-ef213c91a572.png)
![image](https://cloud.githubusercontent.com/assets/9734724/5608332/86e26ec4-94bb-11e4-93c8-9eab1aa16b3e.png)
同一位老师，动态评分不正确，一个为五钻，一个为一颗红心。

**Comment by zariczhu** [comment]
done
