### ISSUE TITLE
前后台数据不同步

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#546]
![image](https://cloud.githubusercontent.com/assets/9734724/5609981/a551d6f6-94e8-11e4-81a7-5f97f8ed5ded.png)
后台状态已改为“正在处理中”，前台状态未改变
![image](https://cloud.githubusercontent.com/assets/9734724/5610005/fa467a68-94e8-11e4-9450-f23ae98aea9e.png)

**Comment by zariczhu** [comment]
无法重现
