### ISSUE TITLE
后台退款管理

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#547]
![image](https://cloud.githubusercontent.com/assets/9734724/5610009/08d33eb8-94e9-11e4-8fba-d38cb95339b1.png)
选择交易状态，点击“退款申请中”“退款完成”，出现到投诉管理页面。
![image](https://cloud.githubusercontent.com/assets/9734724/5610010/0f827cd8-94e9-11e4-9ad3-49fc236d3a1f.png)
字段格式排版，错别字。

**Comment by HillsideHung** [comment]
fixed 错别字和跳转. 请保军看一下字段格式排版.
