### ISSUE TITLE
注册BUG

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#548]
邮箱注册后绑定了手机号码。用手机号码登录，系统提示没有此账户；用手机号码注册，系统提示号码已经注册。（IE11 18721678626 ）
![image](https://cloud.githubusercontent.com/assets/9734724/6053244/e0870dee-ad17-11e4-9ea7-69e85c0888c2.png)
![image](https://cloud.githubusercontent.com/assets/9734724/6053254/f3a8b5f8-ad17-11e4-866c-8f628934abee.png)

**Comment by zariczhu** [comment]
不能重现，添加了log，以后再现可以调查
