### ISSUE TITLE
手机验证BUG

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#549]
手机验证出现的提示，不符合实际情况。比如：请输入验证码。(IE11 18888295437 echo404158)
另外，尝试了很多次，无法接收到手机验证码，不知是什么原因?
![image](https://cloud.githubusercontent.com/assets/9734724/6053421/044957a8-ad1a-11e4-91cd-40c9a78b6b47.png)

**Comment by zariczhu** [comment]
无法重现
