### ISSUE TITLE
课程保存新增bug

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#555]
出现了这样一个情况：当课程取消申请没有被确认的时候，可授课时间是[-],无法保存新增。（IE11 1049735891@qq.com echo404158 ）
![image](https://cloud.githubusercontent.com/assets/9734724/6054086/acbec87e-ad23-11e4-9c4d-9fc90737e990.png)
![image](https://cloud.githubusercontent.com/assets/9734724/6054190/34414244-ad25-11e4-9e47-94944848ccfb.png)
![image](https://cloud.githubusercontent.com/assets/9734724/6054196/3a3d4e22-ad25-11e4-80aa-5b3b54af25d2.png)

**Comment by zariczhu** [comment]
可授课时间 为空 是网速慢引起的，这里是动态加载的
购买或者取消没有被确认，是不可以修改课程内容的
