### ISSUE TITLE
回复需求

### ISSUE THREAD

**Issue by pl01956257** [wulixu/webedu#558]
点击回复，下方出现对号；关闭后，再次点开，下方还是有对号，但是回复按钮不管用登录另一个账号，查看回复但是回复信息为0。（IE11 1049735891@qq.com echo404158(发布需求) 1727843049@qq.com echo404158（回复需求））
![image](https://cloud.githubusercontent.com/assets/9734724/6054759/dabd81b2-ad2c-11e4-832d-a26c9faaacda.png)
![image](https://cloud.githubusercontent.com/assets/9734724/6054762/e7001584-ad2c-11e4-889a-3fb3c29688f1.png)
![image](https://cloud.githubusercontent.com/assets/9734724/6054802/5f8c0d14-ad2d-11e4-9dfe-1e91199c2397.png)

**Comment by zariczhu** [comment]
不能重现
