### ISSUE TITLE
我的购物车--选择部分订单结算错误统计了所有订单

### ISSUE THREAD

**Issue by tonychenta** [wulixu/webedu#62]
![default](https://cloud.githubusercontent.com/assets/8265135/3827711/7fa5e69e-1d70-11e4-914f-e4b0a86ebe4d.png)

**Comment by zariczhu** [comment]
fixed

**Comment by tonychenta** [comment]
还有个错误，
![111](https://cloud.githubusercontent.com/assets/8265135/3852547/15b19678-1ead-11e4-9665-f484d0df6d54.png)
