### ISSUE TITLE
财务信息--查看订单功能没有实现

### ISSUE THREAD

**Issue by tonychenta** [wulixu/webedu#67]
![yyy](https://cloud.githubusercontent.com/assets/8265135/3836664/d4a06a0c-1dd9-11e4-8774-729870bfea82.png)

**Comment by zariczhu** [comment]
fixed

**Comment by tonychenta** [comment]
如果是公益课程，点击后跳转到默认的收费课程页面

**Comment by zariczhu** [comment]
fixed
