### ISSUE TITLE
财务信息--统计老师的收入信息表述不准确

### ISSUE THREAD

**Issue by tonychenta** [wulixu/webedu#70]
![default](https://cloud.githubusercontent.com/assets/8265135/3836861/56a95b5e-1dde-11e4-9f22-6543a073b2d5.png)

**Comment by tonychenta** [comment]
上面的图错了，是下面这个图

![111](https://cloud.githubusercontent.com/assets/8265135/3836872/a7237f4c-1dde-11e4-9e7b-a21218b2aca0.png)

**Comment by zariczhu** [comment]
fixed
