### ISSUE TITLE
个人信息模块--保存个人信息时，设必填项为空，保存失败提示信息不正确

### ISSUE THREAD

**Issue by tonychenta** [wulixu/webedu#8]
当设昵称为空时，点击保存，报错提示信息应为“请输入真是姓名”，而不应该是“请输入登录邮箱”；其他必填选项有同样错误。
![2014_07_26_00_33_01_121](https://cloud.githubusercontent.com/assets/8265135/3705259/d9aab24e-141c-11e4-9f59-804172146669.png)

**Comment by xubaojun** [comment]
已经更新。

**Comment by tonychenta** [comment]
昵称，国家等等几个提示都没有改，你只改了图上显示的一个
