### ISSUE TITLE
学生模式应表述为总学习时长

### ISSUE THREAD

**Issue by tonychenta** [wulixu/webedu#85]
![default](https://cloud.githubusercontent.com/assets/8265135/3851977/1603010a-1ea0-11e4-8829-be1fa43ab456.png)

跟原图对比，表情图样也有区别，斟酌是否需要调整

**Comment by tonychenta** [comment]
设计原图
![default](https://cloud.githubusercontent.com/assets/8265135/3851995/87a39c5c-1ea0-11e4-96e7-23979b1340aa.png)

**Comment by xubaojun** [comment]
目前的是新的设计图，你后面的是原先的设计。
