### ISSUE TITLE
UI错误--个人中心

### ISSUE THREAD

**Issue by tonychenta** [wulixu/webedu#91]
错误1：
![111](https://cloud.githubusercontent.com/assets/8265135/3852908/6ccfd27c-1eb6-11e4-9114-dc721c648695.png)
错误2：

![222](https://cloud.githubusercontent.com/assets/8265135/3852917/bdc8bff4-1eb6-11e4-9957-c93d3b1771df.png)

**Comment by zariczhu** [comment]
如果到个人中心里，把我是学生 高亮去掉
